micronaut:
  application:
    name: restApi
datasources:
  default:
    url: jdbc:mysql://localhost:3306/
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
jpa.default.properties.hibernate.hbm2ddl.auto: update
netty:
  default:
    allocator:
      max-order: 3
